const TABLE_DEFS = {
  Level: {
    file: "Level.csv",
    required: true,
    owner: "Lead Designer",
    headers: [
      "level_id",
      "chapter_id",
      "level_index",
      "level_name",
      "template_id",
      "map_id",
      "wave_group_id",
      "objective_group_id",
      "reward_id",
      "star_rule_id",
      "modifier_id",
      "difficulty",
      "unlock_level_id",
      "enabled",
      "notes",
    ],
    requiredFields: [
      "level_id",
      "chapter_id",
      "level_index",
      "template_id",
      "map_id",
      "wave_group_id",
      "objective_group_id",
      "reward_id",
      "difficulty",
      "enabled",
    ],
    ints: ["chapter_id", "level_index"],
    numbers: ["difficulty"],
    booleans: ["enabled"],
    unique: [["level_id"]],
  },
  LevelTemplate: {
    file: "LevelTemplate.csv",
    required: true,
    owner: "Lead Designer",
    headers: [
      "template_id",
      "template_type",
      "default_ui_rule",
      "default_camera_rule",
      "default_spawn_rule",
      "default_lose_condition",
      "time_limit",
      "enabled",
      "notes",
    ],
    requiredFields: [
      "template_id",
      "template_type",
      "default_ui_rule",
      "default_camera_rule",
      "default_spawn_rule",
      "default_lose_condition",
      "enabled",
    ],
    numbers: ["time_limit"],
    booleans: ["enabled"],
    unique: [["template_id"]],
    recommendedEnums: {
      template_type: [
        "battle",
        "survival",
        "boss",
        "puzzle",
        "platform",
        "roguelite_room",
        "quest",
        "endless",
      ],
    },
  },
  LevelObjective: {
    file: "LevelObjective.csv",
    required: true,
    owner: "Lead Designer",
    headers: [
      "objective_group_id",
      "objective_id",
      "objective_type",
      "target_id",
      "target_count",
      "time_limit",
      "required",
      "enabled",
      "notes",
    ],
    requiredFields: ["objective_group_id", "objective_id", "objective_type", "required", "enabled"],
    ints: ["target_count"],
    numbers: ["time_limit"],
    booleans: ["required", "enabled"],
    unique: [["objective_id"]],
    recommendedEnums: {
      objective_type: [
        "kill_all",
        "kill_enemy",
        "survive_time",
        "protect_target",
        "collect_item",
        "reach_point",
      ],
    },
  },
  Wave: {
    file: "Wave.csv",
    required: true,
    owner: "Level Designer",
    headers: [
      "wave_group_id",
      "wave_id",
      "order_index",
      "start_delay",
      "next_wave_rule",
      "next_wave_param",
      "enabled",
      "notes",
    ],
    requiredFields: ["wave_group_id", "wave_id", "order_index", "next_wave_rule", "enabled"],
    ints: ["order_index"],
    numbers: ["start_delay"],
    booleans: ["enabled"],
    unique: [["wave_id"]],
    recommendedEnums: {
      next_wave_rule: ["kill_all", "time_pass", "manual_trigger", "boss_dead", "none"],
    },
  },
  Spawn: {
    file: "Spawn.csv",
    required: true,
    owner: "Level Designer",
    headers: [
      "wave_id",
      "spawn_id",
      "spawn_time",
      "map_point_id",
      "enemy_group_id",
      "count",
      "interval",
      "formation_id",
      "spawn_rule",
      "enabled",
      "notes",
    ],
    requiredFields: ["wave_id", "spawn_id", "spawn_time", "enemy_group_id", "count", "spawn_rule", "enabled"],
    ints: ["count"],
    numbers: ["spawn_time", "interval"],
    booleans: ["enabled"],
    unique: [["spawn_id"]],
    recommendedEnums: {
      spawn_rule: ["fixed", "weighted", "random_point", "loop", "burst"],
    },
  },
  EnemyGroup: {
    file: "EnemyGroup.csv",
    required: true,
    owner: "Level Designer",
    headers: [
      "enemy_group_id",
      "entry_index",
      "enemy_id",
      "weight",
      "level_multiplier",
      "hp_multiplier",
      "atk_multiplier",
      "enabled",
      "notes",
    ],
    requiredFields: ["enemy_group_id", "entry_index", "enemy_id", "enabled"],
    ints: ["entry_index"],
    numbers: ["weight", "level_multiplier", "hp_multiplier", "atk_multiplier"],
    booleans: ["enabled"],
  },
  Enemy: {
    file: "Enemy.csv",
    required: true,
    owner: "Lead Designer",
    headers: [
      "enemy_id",
      "prefab_id",
      "enemy_type",
      "base_hp",
      "base_atk",
      "move_speed",
      "ai_type",
      "drop_group_id",
      "enabled",
      "notes",
    ],
    requiredFields: ["enemy_id", "prefab_id", "enemy_type", "base_hp", "base_atk", "move_speed", "ai_type", "enabled"],
    numbers: ["base_hp", "base_atk", "move_speed"],
    booleans: ["enabled"],
    unique: [["enemy_id"]],
    recommendedEnums: {
      enemy_type: ["normal", "elite", "boss", "summon"],
    },
  },
  Map: {
    file: "Map.csv",
    required: true,
    owner: "Level Designer",
    headers: [
      "map_id",
      "scene_id",
      "player_spawn_point",
      "camera_rule",
      "bgm_id",
      "boundary_id",
      "enabled",
      "notes",
    ],
    requiredFields: ["map_id", "scene_id", "player_spawn_point", "camera_rule", "enabled"],
    booleans: ["enabled"],
    unique: [["map_id"]],
  },
  MapPoint: {
    file: "MapPoint.csv",
    required: true,
    owner: "Level Designer",
    headers: ["map_id", "point_id", "point_type", "x", "y", "rotation", "tags", "enabled", "notes"],
    requiredFields: ["map_id", "point_id", "point_type", "x", "y", "enabled"],
    numbers: ["x", "y", "rotation"],
    booleans: ["enabled"],
    unique: [["point_id"]],
    recommendedEnums: {
      point_type: ["player_spawn", "enemy_spawn", "trigger", "reward", "npc", "camera"],
    },
  },
  Formation: {
    file: "Formation.csv",
    required: false,
    owner: "Level Designer",
    headers: ["formation_id", "slot_index", "offset_x", "offset_y", "rotation", "enabled", "notes"],
    requiredFields: ["formation_id", "slot_index", "offset_x", "offset_y", "enabled"],
    ints: ["slot_index"],
    numbers: ["offset_x", "offset_y", "rotation"],
    booleans: ["enabled"],
  },
  Reward: {
    file: "Reward.csv",
    required: true,
    owner: "Lead Designer",
    headers: ["reward_id", "gold", "exp", "drop_group_id", "first_clear_reward_id", "enabled", "notes"],
    requiredFields: ["reward_id", "enabled"],
    ints: ["gold", "exp"],
    booleans: ["enabled"],
    unique: [["reward_id"]],
  },
  StarRule: {
    file: "StarRule.csv",
    required: false,
    owner: "Lead Designer",
    headers: ["star_rule_id", "star_index", "condition_type", "condition_param", "reward_id", "enabled", "notes"],
    requiredFields: ["star_rule_id", "star_index", "condition_type", "enabled"],
    ints: ["star_index"],
    booleans: ["enabled"],
  },
  DropGroup: {
    file: "DropGroup.csv",
    required: false,
    owner: "Lead Designer",
    headers: ["drop_group_id", "entry_index", "item_id", "count", "weight", "enabled", "notes"],
    requiredFields: ["drop_group_id", "entry_index", "item_id", "count", "enabled"],
    ints: ["entry_index", "count"],
    numbers: ["weight"],
    booleans: ["enabled"],
  },
  LevelModifier: {
    file: "LevelModifier.csv",
    required: false,
    owner: "Lead Designer",
    headers: [
      "modifier_id",
      "enemy_hp_ratio",
      "enemy_atk_ratio",
      "spawn_speed_ratio",
      "time_limit_delta",
      "player_buff_id",
      "special_rule",
      "enabled",
      "notes",
    ],
    requiredFields: ["modifier_id", "enabled"],
    numbers: ["enemy_hp_ratio", "enemy_atk_ratio", "spawn_speed_ratio", "time_limit_delta"],
    booleans: ["enabled"],
    unique: [["modifier_id"]],
  },
};

module.exports = {
  TABLE_DEFS,
};
