const { TABLE_DEFS } = require("./table-defs");
const { toCamelCase, toLowerCamelCase } = require("./utils");

const INTERFACE_NAMES = {
  Level: "LevelConfig",
  LevelTemplate: "LevelTemplateConfig",
  LevelObjective: "LevelObjectiveConfig",
  Wave: "WaveConfig",
  Spawn: "SpawnConfig",
  EnemyGroup: "EnemyGroupEntryConfig",
  Enemy: "EnemyConfig",
  Map: "MapConfig",
  MapPoint: "MapPointConfig",
  Formation: "FormationSlotConfig",
  Reward: "RewardConfig",
  StarRule: "StarRuleConfig",
  DropGroup: "DropGroupEntryConfig",
  LevelModifier: "LevelModifierConfig",
};

function generateTypesSource() {
  const lines = [];

  lines.push("// Generated by cocos-studio-ouguowen/scripts/export-level-types.js");
  lines.push("// Do not edit manually. Regenerate when the schema changes.");
  lines.push("");
  lines.push("export interface GeneratedConfigMetadata {");
  lines.push("  readonly schema: string;");
  lines.push("  readonly sourceDir: string;");
  lines.push("  readonly generatedAt: string;");
  lines.push("}");
  lines.push("");
  lines.push("export type IdLookup<T> = Readonly<Record<string, T>>;");
  lines.push("export type GroupLookup<T> = Readonly<Record<string, readonly T[]>>;");
  lines.push("");

  for (const [tableName, def] of Object.entries(TABLE_DEFS)) {
    lines.push(`export interface ${INTERFACE_NAMES[tableName]} {`);
    for (const field of def.headers) {
      const propertyName = toCamelCase(field);
      const propertyType = inferFieldType(field, def);
      lines.push(`  readonly ${propertyName}: ${propertyType};`);
    }
    lines.push("}");
    lines.push("");
  }

  lines.push("export interface GeneratedLevelConfigTables {");
  for (const tableName of Object.keys(TABLE_DEFS)) {
    lines.push(
      `  readonly ${toLowerCamelCase(tableName)}: readonly ${INTERFACE_NAMES[tableName]}[];`
    );
  }
  lines.push("}");
  lines.push("");

  lines.push("export interface GeneratedLevelConfigLookups {");
  lines.push("  readonly levelsById: IdLookup<LevelConfig>;");
  lines.push("  readonly templatesById: IdLookup<LevelTemplateConfig>;");
  lines.push("  readonly enemiesById: IdLookup<EnemyConfig>;");
  lines.push("  readonly mapsById: IdLookup<MapConfig>;");
  lines.push("  readonly rewardsById: IdLookup<RewardConfig>;");
  lines.push("  readonly modifiersById: IdLookup<LevelModifierConfig>;");
  lines.push("}");
  lines.push("");

  lines.push("export interface GeneratedLevelConfigGroups {");
  lines.push("  readonly objectivesByGroup: GroupLookup<LevelObjectiveConfig>;");
  lines.push("  readonly wavesByGroup: GroupLookup<WaveConfig>;");
  lines.push("  readonly spawnsByWave: GroupLookup<SpawnConfig>;");
  lines.push("  readonly enemyEntriesByGroup: GroupLookup<EnemyGroupEntryConfig>;");
  lines.push("  readonly formationsById: GroupLookup<FormationSlotConfig>;");
  lines.push("  readonly starRulesById: GroupLookup<StarRuleConfig>;");
  lines.push("  readonly dropEntriesByGroup: GroupLookup<DropGroupEntryConfig>;");
  lines.push("}");
  lines.push("");

  lines.push("export interface GeneratedLevelConfig {");
  lines.push("  readonly metadata: GeneratedConfigMetadata;");
  lines.push("  readonly tables: GeneratedLevelConfigTables;");
  lines.push("  readonly lookups: GeneratedLevelConfigLookups;");
  lines.push("  readonly groups: GeneratedLevelConfigGroups;");
  lines.push("}");
  lines.push("");

  return `${lines.join("\n")}\n`;
}

function inferFieldType(field, def) {
  let baseType = "string";

  if ((def.booleans || []).includes(field)) {
    baseType = "boolean";
  } else if ((def.ints || []).includes(field) || (def.numbers || []).includes(field)) {
    baseType = "number";
  } else if (field === "tags") {
    baseType = "readonly string[]";
  }

  if (field === "tags") {
    return shouldAllowNull(field, def) ? `${baseType} | null` : baseType;
  }

  return shouldAllowNull(field, def) ? `${baseType} | null` : baseType;
}

function shouldAllowNull(field, def) {
  return !(def.requiredFields || []).includes(field);
}

module.exports = {
  generateTypesSource,
};
